### ISSUE TITLE
[API] Clojure names

### ISSUE THREAD

**Issue by JustusAdam** [ohua-dev/ohua-jvm-integration#15]
In the old compiler we would register each stateful function also with a 'clojurized' name. Aka `oneToN` would also be available under `one-to-n`.

Do we wish to keep that (then I'd have to add it back in) or do we want to only use the name given to the function?

**Comment by sertel** [comment]
I would keep it simple and would not convert function names anymore.

**Comment by JustusAdam** [comment]
I would tend to agree.
