### ISSUE TITLE
[Feature] Env arc coersion

### ISSUE THREAD

**Issue by JustusAdam** [ohua-dev/ohua-jvm-integration#8]
Subtrees which are composed entirely of environment expressions should be coerced into just one env expression.

Make sure this is done right after creating ALang itself. We might loose opportunities for performing this after doing reordering.
Perhaps it may be useful even to do this once of more times later in addition.

**Comment by sertel** [comment]
What is an environment expression?
Can you give an example?
As far as I understand, there are only environment variables. Everything else is a call to a Clojure function.

**Comment by JustusAdam** [comment]
Sure but something like `(+ 1 1)` can be `(__callClojureFunction + (env 1) (env 1))` or we coerce this into `(env (+ 1 1))`.
Of course this only works if the entire expression is made up of environment args. (Such as `+` and `1`)

**Comment by JustusAdam** [comment]
We chose not to to this for now, as this may lead to unexpected behaviour from the point of the programmer.

This is to be picked up again when we start dealing with fusion.
